In [1]:
import pandas as pd

In [2]:
# Clean 2020 Jan - May crime data

crime_2020_df = pd.read_csv("raw_data/2020_1-5_Jan-May.csv")
crime_2020_df = crime_2020_df.rename(columns={"Occurrence\nDate": "Date", 
                                              "Occurrence\nHour": "Hour",
                                              "NIBRS\nClass": "NIBRS_Class",
                                              "NIBRSDescription": "Offense_Type",
                                              "Offense\nCount": "Offense_Count",
                                              "Block Range": "Block_Range",
                                              "StreetName": "Street_Name",
                                              "Street\nType": "Street_Type",
                                              "ZIP Code": "Zip_Code"})
crime_2020_df.columns

Index(['Incident', 'Date', 'Hour', 'NIBRS_Class', 'Offense_Type',
       'Offense_Count', 'Beat', 'Premise', 'Block_Range', 'Street_Name',
       'Street_Type', 'Suffix', 'City', 'Zip_Code'],
      dtype='object')

In [3]:
# Only take 2020 data we need
crime_2020_df = crime_2020_df[['Date','Hour','Offense_Type','Offense_Count','Premise','Block_Range','Street_Name','Street_Type','City']]
crime_2020_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,1/1/20,0,Theft of motor vehicle parts or accessory,1,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON
1,1/1/20,0,Aggravated Assault,1,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON
2,1/1/20,0,"Destruction, damage, vandalism",1,"Residence, Home (Includes Apartment)",8064,LENORE,NaN,HOUSTON
3,1/1/20,0,Simple assault,1,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON
4,1/1/20,0,"Destruction, damage, vandalism",1,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON
...,...,...,...,...,...,...,...,...,...
86909,5/31/20,23,Theft of motor vehicle parts or accessory,1,"Parking Lot, Garage",16501,CENTRAL GREEN,BLVD,HOUSTON
86910,5/31/20,23,Theft from motor vehicle,1,"Parking Lot, Garage",7815,WILLOW CHASE,BLVD,HOUSTON
86911,5/31/20,23,Intimidation,1,"Residence, Home (Includes Apartment)",9550,ELLA LEE,LN,HOUSTON
86912,5/31/20,23,Motor vehicle theft,1,"Parking Lot, Garage",10000,FANNIN,ST,HOUSTON
86913,5/31/20,23,Theft from motor vehicle,1,"Parking Lot, Garage",10421,CLAY,RD,HOUSTON

In [4]:
# Clean 2019 Jan - Dec crime data

crime_2019_df = pd.read_csv("raw_data/2019_1-12_Jan-Dec.csv")
crime_2019_df = crime_2019_df.rename(columns={"Occurrence\nDate": "Date", 
                                              "Occurrence\nHour": "Hour",
                                              "NIBRS\nClass": "NIBRS_Class",
                                              "NIBRSDescription": "Offense_Type",
                                              "Offense\nCount": "Offense_Count",
                                              "Block Range": "Block_Range",
                                              "StreetName": "Street_Name",
                                              "Street\nType": "Street_Type",
                                              "ZIP Code": "Zip_Code"})
crime_2019_df.columns

Index(['Incident', 'Date', 'Hour', 'NIBRS_Class', 'Offense_Type',
       'Offense_Count', 'Beat', 'Premise', 'Block_Range', 'Street_Name',
       'Street_Type', 'Suffix', 'City', 'Zip_Code'],
      dtype='object')

In [5]:
# Only take 2019 data we need
crime_2019_df = crime_2019_df[['Date','Hour','Offense_Type','Offense_Count','Premise','Block_Range','Street_Name','Street_Type','City']]
crime_2019_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,1/1/19,0,"Destruction, damage, vandalism",1,"Residence, Home (Includes Apartment)",9622,SAN CARLOS,NaN,HOUSTON
1,1/1/19,0,"Drug, narcotic violations",1,"Highway, Road, Street, Alley",NaN,EAST,FWY,HOUSTON
2,1/1/19,0,"Destruction, damage, vandalism",1,"Residence, Home (Includes Apartment)",16718,LONE QUAIL,CT,HOUSTON
3,1/1/19,0,Weapon law violations,1,"Residence, Home (Includes Apartment)",1909,MELBOURNE,NaN,HOUSTON
4,1/1/19,0,Aggravated Assault,1,"Residence, Home (Includes Apartment)",4034,OSBY,DR,HOUSTON
...,...,...,...,...,...,...,...,...,...
219029,12/31/19,23,Simple assault,1,"Residence, Home (Includes Apartment)",3809,SOUTHLAWN,ST,HOUSTON
219030,12/31/19,23,Aggravated Assault,1,"Residence, Home (Includes Apartment)",6600,HILLCROFT,AVE,HOUSTON
219031,12/31/19,23,Shoplifting,1,Convenience Store,2724,QUITMAN,ST,HOUSTON
219032,12/31/19,23,Intimidation,1,"Highway, Road, Street, Alley",9400,GULF,FWY,HOUSTON
219033,12/31/19,23,"Drug, narcotic violations",1,"Highway, Road, Street, Alley",9400,GULF,FWY,HOUSTON

In [6]:
# Clean 2018 Jan - May crime data
# Need to seperate 2018 data from first half and second half of the year due to different formatting of columns 

all_files = ["raw_data/2018_1_Jan.csv", 
            "raw_data/2018_2_Feb.csv",
            "raw_data/2018_3_Mar.csv",
            "raw_data/2018_4_Apr.csv",
            "raw_data/2018_5_May.csv"]

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

crime_2018_Jan_May_df = pd.concat(li, axis=0, ignore_index=True)
crime_2018_Jan_May_df = crime_2018_Jan_May_df.rename(columns={"Offense Type": "Offense_Type",
                                                              "Block Range": "Block_Range",
                                                              "Street Name": "Street_Name",
                                                              "Street\nType": "Street_Type",
                                                              "Type": "Street_Type",
                                                              "Offenses": "Offense_Count"})
crime_2018_Jan_May_df.columns

Index(['Date', 'Hour', 'Offense_Type', 'Beat', 'Premise', 'Block_Range',
       'Street_Name', 'Street_Type', 'Suffix', 'Offense_Count'],
      dtype='object')

In [7]:
# Only take 2018 Jan-May data we need
crime_2018_Jan_May_df = crime_2018_Jan_May_df[['Date','Hour','Offense_Type','Offense_Count','Premise','Block_Range','Street_Name','Street_Type']]
crime_2018_Jan_May_df['City'] = 'HOUSTON'
crime_2018_Jan_May_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,01/01/2018,18.0,Robbery,1.0,"Field, Woods, Forest, Park",200-299,LENOX,-,HOUSTON
1,01/01/2018,18.0,Theft,1.0,"Road, Street, or Sidewalk",3700-3799,HOUSTON LAKE,DR,HOUSTON
2,01/02/2018,14.0,Theft,1.0,Auto Repair,16700-16799,EASTEX,-,HOUSTON
3,01/04/2018,8.0,Burglary,1.0,Auto Repair,4700-4799,HARRISBURG,BLVD,HOUSTON
4,01/04/2018,18.0,Theft,1.0,Department or Discount Store,5100-5199,HARRISBURG,BLVD,HOUSTON
...,...,...,...,...,...,...,...,...,...
47015,05/28/2018,22.0,Theft,1.0,Apartment Parking Lot,17700-17799,EASTEX,FWY,HOUSTON
47016,05/28/2018,22.0,Theft,1.0,Other Parking Lot,900-999,ST EMANUEL,-,HOUSTON
47017,05/30/2018,23.0,AutoTheft,1.0,Service or Gas Station,10800-10899,SHADY,LN,HOUSTON
47018,05/30/2018,5.0,Theft,1.0,Grocery Store or Supermarket,600-699,VICTORY,DR,HOUSTON
47019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HOUSTON

In [8]:
# Clean 2018 June - Dec crime data

all_files = ["raw_data/2018_6_Jun.csv", 
            "raw_data/2018_7_Jul.csv",
            "raw_data/2018_8_Aug.csv",
            "raw_data/2018_9_Sep.csv",
            "raw_data/2018_10_Oct.csv",
            "raw_data/2018_11_Nov.csv",
            "raw_data/2018_12_Dec.csv"]

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

crime_2018_Jun_Dec_df = pd.concat(li, axis=0, ignore_index=True)
crime_2018_Jun_Dec_df = crime_2018_Jun_Dec_df.rename(columns={"Occurrence Date": "Date",
                                                              "Occurrence Hour": "Hour",
                                                              "NIBRS Description": "Offense_Type",
                                                              "Offense Count": "Offense_Count",
                                                              "Block Range": "Block_Range",
                                                              "Street Name": "Street_Name",
                                                              "Street Type": "Street_Type"})
crime_2018_Jun_Dec_df.columns

Index(['Date', 'Hour', 'Offense_Type', 'Unnamed: 3', 'Offense_Count', 'Beat',
       'Premise', 'Block_Range', 'Street_Name', 'Street_Type', 'Suffix'],
      dtype='object')

In [9]:
# Only take 2018 Jun-Dec data we need
crime_2018_Jun_Dec_df = crime_2018_Jun_Dec_df[['Date','Hour','Offense_Type','Offense_Count','Premise','Block_Range','Street_Name','Street_Type']]
crime_2018_Jun_Dec_df['City'] = 'HOUSTON'
crime_2018_Jun_Dec_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,6/1/18,0,Simple assault,1,"Drug Store, Doctors Office, Hospital",6600-6699,FANNIN,ST,HOUSTON
1,6/1/18,0,"False pretenses, swindle",1,"Residence, Home (Includes Apartment)",8100-8199,MILREDGE,ST,HOUSTON
2,6/1/18,0,All other offenses,1,"Highway, Road, Street, Alley",6400-6499,BELLFORT,AVE,HOUSTON
3,6/1/18,0,Motor vehicle theft,1,"Highway, Road, Street, Alley",8400-8499,FUQUA,ST,HOUSTON
4,6/1/18,0,"Burglary, Breaking and Entering",1,"Residence, Home (Includes Apartment)",4000-4099,FANNIN,ST,HOUSTON
...,...,...,...,...,...,...,...,...,...
145708,12/31/18,23,Aggravated Assault,1,"Residence, Home (Includes Apartment)",3900-3999,GRAPEVINE,ST,HOUSTON
145709,12/31/18,23,Driving under the influence,1,"Highway, Road, Street, Alley",7800-7899,IH 10,FWY,HOUSTON
145710,12/31/18,23,Driving under the influence,1,"Highway, Road, Street, Alley",1300-1399,ST JOSEPH,PKWY,HOUSTON
145711,12/31/18,23,"Drug, narcotic violations",1,"Parking Lot, Garage",5600-5699,CHIMNEY ROCK,RD,HOUSTON
145712,12/31/18,23,Disorderly conduct,1,"Parking Lot, Garage",5600-5699,CHIMNEY ROCK,RD,HOUSTON

In [10]:
clean_crime_data_df = pd.concat([crime_2020_df, 
                                 crime_2019_df,
                                 crime_2018_Jan_May_df, 
                                 crime_2018_Jun_Dec_df,], ignore_index=True)

In [11]:
clean_crime_data_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,NaN,HOUSTON
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON
...,...,...,...,...,...,...,...,...,...
498676,12/31/18,23.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",3900-3999,GRAPEVINE,ST,HOUSTON
498677,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",7800-7899,IH 10,FWY,HOUSTON
498678,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",1300-1399,ST JOSEPH,PKWY,HOUSTON
498679,12/31/18,23.0,"Drug, narcotic violations",1.0,"Parking Lot, Garage",5600-5699,CHIMNEY ROCK,RD,HOUSTON
498680,12/31/18,23.0,Disorderly conduct,1.0,"Parking Lot, Garage",5600-5699,CHIMNEY ROCK,RD,HOUSTON

In [12]:
import numpy as np

clean_crime_data_df['Street_Type'] = clean_crime_data_df['Street_Type'].replace(np.nan, '', regex=True)

clean_crime_data_df = clean_crime_data_df.astype(str)

clean_crime_data_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,,HOUSTON
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON
...,...,...,...,...,...,...,...,...,...
498676,12/31/18,23.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",3900-3999,GRAPEVINE,ST,HOUSTON
498677,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",7800-7899,IH 10,FWY,HOUSTON
498678,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",1300-1399,ST JOSEPH,PKWY,HOUSTON
498679,12/31/18,23.0,"Drug, narcotic violations",1.0,"Parking Lot, Garage",5600-5699,CHIMNEY ROCK,RD,HOUSTON
498680,12/31/18,23.0,Disorderly conduct,1.0,"Parking Lot, Garage",5600-5699,CHIMNEY ROCK,RD,HOUSTON

In [13]:
clean_crime_data_df['Block_Range'] = clean_crime_data_df['Block_Range'].apply(lambda x: x.split('-')[0])
clean_crime_data_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,,HOUSTON
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON
...,...,...,...,...,...,...,...,...,...
498676,12/31/18,23.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,HOUSTON
498677,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",7800,IH 10,FWY,HOUSTON
498678,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",1300,ST JOSEPH,PKWY,HOUSTON
498679,12/31/18,23.0,"Drug, narcotic violations",1.0,"Parking Lot, Garage",5600,CHIMNEY ROCK,RD,HOUSTON
498680,12/31/18,23.0,Disorderly conduct,1.0,"Parking Lot, Garage",5600,CHIMNEY ROCK,RD,HOUSTON

In [14]:
clean_crime_data_df['State'] = 'TX'
clean_crime_data_df.head()

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON,TX
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON,TX
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,,HOUSTON,TX
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON,TX
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON,TX

In [15]:
clean_crime_data_df['Street_Address'] = clean_crime_data_df['Block_Range'] + ' ' + clean_crime_data_df['Street_Name'] + ' ' + clean_crime_data_df['Street_Type']

clean_crime_data_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON,TX,9311 BELLA PINE CT
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON,TX,8701 GUSTINE LN
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,,HOUSTON,TX,8064 LENORE
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON,TX,5930 DASHWOOD DR
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON,TX,5218 KENILWOOD DR
...,...,...,...,...,...,...,...,...,...,...,...
498676,12/31/18,23.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,HOUSTON,TX,3900 GRAPEVINE ST
498677,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",7800,IH 10,FWY,HOUSTON,TX,7800 IH 10 FWY
498678,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",1300,ST JOSEPH,PKWY,HOUSTON,TX,1300 ST JOSEPH PKWY
498679,12/31/18,23.0,"Drug, narcotic violations",1.0,"Parking Lot, Garage",5600,CHIMNEY ROCK,RD,HOUSTON,TX,5600 CHIMNEY ROCK RD
498680,12/31/18,23.0,Disorderly conduct,1.0,"Parking Lot, Garage",5600,CHIMNEY ROCK,RD,HOUSTON,TX,5600 CHIMNEY ROCK RD

In [65]:
clean_crime_data_df['Zip_Code'] = ''
clean_crime_data_df

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address,Zip_Code
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON,TX,9311 BELLA PINE CT,
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON,TX,8701 GUSTINE LN,
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,,HOUSTON,TX,8064 LENORE,
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON,TX,5930 DASHWOOD DR,
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON,TX,5218 KENILWOOD DR,
...,...,...,...,...,...,...,...,...,...,...,...,...
498676,12/31/18,23.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,HOUSTON,TX,3900 GRAPEVINE ST,
498677,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",7800,IH 10,FWY,HOUSTON,TX,7800 IH 10 FWY,
498678,12/31/18,23.0,Driving under the influence,1.0,"Highway, Road, Street, Alley",1300,ST JOSEPH,PKWY,HOUSTON,TX,1300 ST JOSEPH PKWY,
498679,12/31/18,23.0,"Drug, narcotic violations",1.0,"Parking Lot, Garage",5600,CHIMNEY ROCK,RD,HOUSTON,TX,5600 CHIMNEY ROCK RD,
498680,12/31/18,23.0,Disorderly conduct,1.0,"Parking Lot, Garage",5600,CHIMNEY ROCK,RD,HOUSTON,TX,5600 CHIMNEY ROCK RD,

In [27]:
offense_types = clean_crime_data_df['Offense_Type'].to_list()
offense_types

['Theft of motor vehicle parts or accessory',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Theft from motor vehicle',
 'Simple assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Drug, narcotic violations',
 'Aggravated Assault',
 'Simple assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Intimidation',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Robbery',
 'Aggravated Assault',
 'Simple assault',
 'Forcible rape',
 'Destruction, damage, vandalism',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Aggravated Assault',
 'Intimidation',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Motor vehicle theft',
 'Credit card, ATM fraud',
 'Motor vehicle theft',
 'Identify theft',
 'Destruction, damage, vandalism',
 'Theft from motor vehicle',
 'All other larceny',
 'Intimidation',
 'Forcible rape',
 'Simple assault',
 'Forcible rape',
 'Forcible sodomy',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Motor vehicle theft',
 'Statutory rape',
 'Burglary, Breaking and Entering',
 'Credit card, ATM fraud',
 'Drug, narcotic violations',
 'Aggravated Assault',
 'Simple assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Simple assault',
 'Drug, narcotic violations',
 'Simple assault',
 'Simple assault',
 'Simple assault',
 'Drug, narcotic violations',
 'Murder, non-negligent',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Intimidation',
 'Aggravated Assault',
 'Motor vehicle theft',
 'All other larceny',
 'All other larceny',
 'Shoplifting',
 'Arson',
 'Theft from motor vehicle',
 'Simple assault',
 'All other larceny',
 'Aggravated Assault',
 'Simple assault',
 'Simple assault',
 'Aggravated Assault',
 'Drug, narcotic violations',
 'Weapon law violations',
 'Drug, narcotic violations',
 'Simple assault',
 'Simple assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Simple assault',
 'Simple assault',
 'Aggravated Assault',
 'Intimidation',
 'Theft of motor vehicle parts or accessory',
 'Motor vehicle theft',
 'Pocket-picking',
 'Aggravated Assault',
 'Aggravated Assault',
 'Robbery',
 'Simple assault',
 'Aggravated Assault',
 'Intimidation',
 'Aggravated Assault',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Simple assault',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Aggravated Assault',
 'Aggravated Assault',
 'Aggravated Assault',
 'All other larceny',
 'Robbery',
 'Robbery',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'All other larceny',
 'Burglary, Breaking and Entering',
 'Robbery',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Theft of motor vehicle parts or accessory',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Simple assault',
 'Robbery',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'Simple assault',
 'All other larceny',
 'Simple assault',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Robbery',
 'Weapon law violations',
 'Simple assault',
 'Aggravated Assault',
 'Simple assault',
 'All other larceny',
 'Simple assault',
 'Forcible sodomy',
 'Robbery',
 'Simple assault',
 'Aggravated Assault',
 'Drug, narcotic violations',
 'Simple assault',
 'All other larceny',
 'Burglary, Breaking and Entering',
 'Aggravated Assault',
 'Robbery',
 'Aggravated Assault',
 'Aggravated Assault',
 'Simple assault',
 'Motor vehicle theft',
 'Shoplifting',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Robbery',
 'Aggravated Assault',
 'Aggravated Assault',
 'Simple assault',
 'Aggravated Assault',
 'Simple assault',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Aggravated Assault',
 'Drug, narcotic violations',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Drug, narcotic violations',
 'Simple assault',
 'Aggravated Assault',
 'Weapon law violations',
 'Simple assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Robbery',
 'Intimidation',
 'Theft from motor vehicle',
 'Simple assault',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Robbery',
 'Aggravated Assault',
 'Counterfeiting, forgery',
 'Simple assault',
 'Simple assault',
 'Aggravated Assault',
 'Simple assault',
 'Simple assault',
 'Robbery',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Robbery',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Aggravated Assault',
 'All other larceny',
 'Simple assault',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Intimidation',
 'Destruction, damage, vandalism',
 'All other larceny',
 'Simple assault',
 'Theft from motor vehicle',
 'Aggravated Assault',
 'Simple assault',
 'Theft from motor vehicle',
 'Destruction, damage, vandalism',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Motor vehicle theft',
 'Identify theft',
 'Burglary, Breaking and Entering',
 'Identify theft',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Aggravated Assault',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Simple assault',
 'Aggravated Assault',
 'Shoplifting',
 'Counterfeiting, forgery',
 'All other larceny',
 'Motor vehicle theft',
 'Forcible sodomy',
 'Intimidation',
 'Motor vehicle theft',
 'Pornographs, obscene material',
 'Intimidation',
 'Theft from motor vehicle',
 'Identify theft',
 'All other larceny',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'All other larceny',
 'Motor vehicle theft',
 'Intimidation',
 'Pornographs, obscene material',
 'Simple assault',
 'Identify theft',
 'Intimidation',
 'Theft from building',
 'Robbery',
 'Forcible sodomy',
 'Intimidation',
 'Simple assault',
 'Theft from motor vehicle',
 'Drug, narcotic violations',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Aggravated Assault',
 'Robbery',
 'All other larceny',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Credit card, ATM fraud',
 'Motor vehicle theft',
 'Simple assault',
 'Shoplifting',
 'Robbery',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Simple assault',
 'Theft from building',
 'Burglary, Breaking and Entering',
 'Robbery',
 'Theft of motor vehicle parts or accessory',
 'Identify theft',
 'All other larceny',
 'Credit card, ATM fraud',
 'Shoplifting',
 'Simple assault',
 'Forcible fondling',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Shoplifting',
 'Simple assault',
 'Shoplifting',
 'Theft of motor vehicle parts or accessory',
 'Shoplifting',
 'Burglary, Breaking and Entering',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Theft from building',
 'Weapon law violations',
 'Motor vehicle theft',
 'Simple assault',
 'Theft from building',
 'Intimidation',
 'Intimidation',
 'Shoplifting',
 'Destruction, damage, vandalism',
 'Intimidation',
 'Aggravated Assault',
 'Simple assault',
 'Shoplifting',
 'Aggravated Assault',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Destruction, damage, vandalism',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Theft from building',
 'Destruction, damage, vandalism',
 'Forcible sodomy',
 'Theft from motor vehicle',
 'Theft of motor vehicle parts or accessory',
 'Credit card, ATM fraud',
 'Theft from motor vehicle',
 'Theft from building',
 'Credit card, ATM fraud',
 'Destruction, damage, vandalism',
 'All other larceny',
 'Intimidation',
 'All other larceny',
 'Intimidation',
 'Intimidation',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Intimidation',
 'Simple assault',
 'Purse-snatching',
 'All other larceny',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Impersonation',
 'Embezzlement',
 'Identify theft',
 'Identify theft',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'Theft from building',
 'Burglary, Breaking and Entering',
 'Burglary, Breaking and Entering',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Credit card, ATM fraud',
 'All other larceny',
 'Intimidation',
 'Motor vehicle theft',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Intimidation',
 'Credit card, ATM fraud',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Simple assault',
 'Simple assault',
 'Simple assault',
 'Purse-snatching',
 'Shoplifting',
 'Theft from motor vehicle',
 'Shoplifting',
 'Simple assault',
 'Simple assault',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Shoplifting',
 'Aggravated Assault',
 'Bribery',
 'All other larceny',
 'Identify theft',
 'Extortion, Blackmail',
 'Intimidation',
 'Aggravated Assault',
 'Simple assault',
 'Aggravated Assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Theft from motor vehicle',
 'Theft from building',
 'Drug, narcotic violations',
 'Simple assault',
 'Shoplifting',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Shoplifting',
 'Aggravated Assault',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'Destruction, damage, vandalism',
 'All other larceny',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Intimidation',
 'Intimidation',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Intimidation',
 'Theft from motor vehicle',
 'Shoplifting',
 'Shoplifting',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Burglary, Breaking and Entering',
 'Motor vehicle theft',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Intimidation',
 'Credit card, ATM fraud',
 'Theft from motor vehicle',
 'Simple assault',
 'Weapon law violations',
 'Drug, narcotic violations',
 'Murder, non-negligent',
 'Robbery',
 'Intimidation',
 'Intimidation',
 'Shoplifting',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Shoplifting',
 'Burglary, Breaking and Entering',
 'Aggravated Assault',
 'Shoplifting',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Motor vehicle theft',
 'Theft from motor vehicle',
 'Theft of motor vehicle parts or accessory',
 'Robbery',
 'Theft from motor vehicle',
 'All other larceny',
 'Theft from motor vehicle',
 'All other larceny',
 'Aggravated Assault',
 'Aggravated Assault',
 'Intimidation',
 'Intimidation',
 'Simple assault',
 'Motor vehicle theft',
 'All other larceny',
 'Destruction, damage, vandalism',
 'Robbery',
 'Intimidation',
 'Intimidation',
 'Intimidation',
 'Shoplifting',
 'Weapon law violations',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Simple assault',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Robbery',
 'Theft from building',
 'Destruction, damage, vandalism',
 'Pocket-picking',
 'Theft of motor vehicle parts or accessory',
 'Destruction, damage, vandalism',
 'Identify theft',
 'Credit card, ATM fraud',
 'Theft from building',
 'All other larceny',
 'Forcible rape',
 'Robbery',
 'Simple assault',
 'Motor vehicle theft',
 'Intimidation',
 'Simple assault',
 'Shoplifting',
 'Intimidation',
 'Intimidation',
 'Aggravated Assault',
 'Shoplifting',
 'Motor vehicle theft',
 'Aggravated Assault',
 'Shoplifting',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Robbery',
 'Theft from building',
 'Robbery',
 'Theft from motor vehicle',
 'Embezzlement',
 'Burglary, Breaking and Entering',
 'False pretenses, swindle',
 'Credit card, ATM fraud',
 'Intimidation',
 'Shoplifting',
 'Simple assault',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Simple assault',
 'Robbery',
 'Aggravated Assault',
 'Shoplifting',
 'Intimidation',
 'Aggravated Assault',
 'Robbery',
 'Destruction, damage, vandalism',
 'Weapon law violations',
 'Intimidation',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft of motor vehicle parts or accessory',
 'Theft of motor vehicle parts or accessory',
 'Intimidation',
 'Motor vehicle theft',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'All other larceny',
 'Forcible fondling',
 'Simple assault',
 'Aggravated Assault',
 'Robbery',
 'Aggravated Assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Drug, narcotic violations',
 'Stolen property offenses',
 'Aggravated Assault',
 'Aggravated Assault',
 'Shoplifting',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Simple assault',
 'Simple assault',
 'Robbery',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Destruction, damage, vandalism',
 'Motor vehicle theft',
 'All other larceny',
 'Simple assault',
 'Motor vehicle theft',
 'Aggravated Assault',
 'All other larceny',
 'Robbery',
 'Robbery',
 'Motor vehicle theft',
 'Robbery',
 'Aggravated Assault',
 'Robbery',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Shoplifting',
 'Shoplifting',
 'Theft from motor vehicle',
 'Intimidation',
 'Motor vehicle theft',
 'Burglary, Breaking and Entering',
 'Theft of motor vehicle parts or accessory',
 'Theft from motor vehicle',
 'Destruction, damage, vandalism',
 'Theft of motor vehicle parts or accessory',
 'Motor vehicle theft',
 'Motor vehicle theft',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft of motor vehicle parts or accessory',
 'Theft from motor vehicle',
 'Simple assault',
 'Robbery',
 'Intimidation',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Simple assault',
 'Intimidation',
 'Intimidation',
 'Simple assault',
 'Aggravated Assault',
 'Robbery',
 'Robbery',
 'Intimidation',
 'Motor vehicle theft',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'Theft from motor vehicle',
 'All other larceny',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Credit card, ATM fraud',
 'Theft from building',
 'Motor vehicle theft',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Robbery',
 'Theft of motor vehicle parts or accessory',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Simple assault',
 'Robbery',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Theft from motor vehicle',
 'Theft of motor vehicle parts or accessory',
 'Motor vehicle theft',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Intimidation',
 'Theft from motor vehicle',
 'Motor vehicle theft',
 'Simple assault',
 'Intimidation',
 'Destruction, damage, vandalism',
 'All other larceny',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Aggravated Assault',
 'Purse-snatching',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Identify theft',
 'False pretenses, swindle',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'Identify theft',
 'Simple assault',
 'Identify theft',
 'All other larceny',
 'All other larceny',
 'Theft of motor vehicle parts or accessory',
 'Destruction, damage, vandalism',
 'Credit card, ATM fraud',
 'Shoplifting',
 'All other larceny',
 'Simple assault',
 'Drug, narcotic violations',
 'Aggravated Assault',
 'Simple assault',
 'Simple assault',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Pornographs, obscene material',
 'Simple assault',
 'Simple assault',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Motor vehicle theft',
 'Simple assault',
 'All other larceny',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Theft of motor vehicle parts or accessory',
 'Counterfeiting, forgery',
 'All other larceny',
 'Intimidation',
 'Simple assault',
 'Theft of motor vehicle parts or accessory',
 'Drug, narcotic violations',
 'Intimidation',
 'Aggravated Assault',
 'Robbery',
 'All other larceny',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Intimidation',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Burglary, Breaking and Entering',
 'Intimidation',
 'Aggravated Assault',
 'Shoplifting',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Intimidation',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'Theft from building',
 'Shoplifting',
 'All other larceny',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'All other larceny',
 'Shoplifting',
 'Robbery',
 'Identify theft',
 'Counterfeiting, forgery',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Simple assault',
 'Burglary, Breaking and Entering',
 'Theft from motor vehicle',
 'Intimidation',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Burglary, Breaking and Entering',
 'Burglary, Breaking and Entering',
 'Identify theft',
 'Motor vehicle theft',
 'Burglary, Breaking and Entering',
 'Motor vehicle theft',
 'Theft of motor vehicle parts or accessory',
 'Burglary, Breaking and Entering',
 'Destruction, damage, vandalism',
 'Human Trafficking/Commercial Sex Act',
 'Forcible sodomy',
 'Forcible rape',
 'Burglary, Breaking and Entering',
 'Counterfeiting, forgery',
 'Theft of motor vehicle parts or accessory',
 'False pretenses, swindle',
 'Impersonation',
 'Simple assault',
 'Simple assault',
 'Destruction, damage, vandalism',
 'Shoplifting',
 'Simple assault',
 'All other larceny',
 'Robbery',
 'Theft from motor vehicle',
 'Shoplifting',
 'Theft from motor vehicle',
 'Intimidation',
 'Robbery',
 'False pretenses, swindle',
 'Theft from motor vehicle',
 'Identify theft',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Theft from motor vehicle',
 'Burglary, Breaking and Entering',
 'Motor vehicle theft',
 'All other larceny',
 'Burglary, Breaking and Entering',
 'All other larceny',
 'Destruction, damage, vandalism',
 'Destruction, damage, vandalism',
 'Theft of motor vehicle parts or accessory',
 'Intimidation',
 'Intimidation',
 'Shoplifting',
 'Shoplifting',
 'Intimidation',
 'Robbery',
 'Robbery',
 'Theft of motor vehicle parts or accessory',

In [59]:
offenses_list = ['Theft of motor vehicle parts or accessory', 'Human Trafficking/Commercial Sex Act', ''
 'Aggravated Assault', 'All other larceny', 'Burglary, Breaking and Entering', 'theft',
 'Destruction, damage, vandalism', 'assault', 'Negligent manslaughter', 'Pocket-picking', 'Purse-snatching', 
 'Simple assault', 'Intimidation', 'Robbery', 'Forcible rape', 'Theft from motor vehicle', 'Motor vehicle theft', 'Statutory rape', 'Murder, non-negligent', ] 
small_crime_data_df = clean_crime_data_df[clean_crime_data_df['Offense_Type'].isin(offenses_list)]
# clean_crime_data_df['Offense_Type'].value_counts()
small_crime_data_df.head()

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address,Zip_Code
0,1/1/20,0.0,Theft of motor vehicle parts or accessory,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,HOUSTON,TX,9311 BELLA PINE CT,
1,1/1/20,0.0,Aggravated Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,HOUSTON,TX,8701 GUSTINE LN,
2,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",8064,LENORE,,HOUSTON,TX,8064 LENORE,
3,1/1/20,0.0,Simple assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,HOUSTON,TX,5930 DASHWOOD DR,
4,1/1/20,0.0,"Destruction, damage, vandalism",1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,HOUSTON,TX,5218 KENILWOOD DR,

In [32]:
geo_df = small_crime_data_df[['Street_Address', 'City', 'State', 'Zip_Code']]

geo_df

               Street_Address     City State Zip_Code
0          9311 BELLA PINE CT  HOUSTON    TX
1             8701 GUSTINE LN  HOUSTON    TX
2                8064 LENORE   HOUSTON    TX
3            5930 DASHWOOD DR  HOUSTON    TX
4           5218 KENILWOOD DR  HOUSTON    TX
...                       ...      ...   ...      ...
498669         7700 AVENUE H   HOUSTON    TX
498670       7100 CULLEN BLVD  HOUSTON    TX
498671  10800 QUILL GARDEN LN  HOUSTON    TX
498672     16300 COVEY RUN DR  HOUSTON    TX
498676      3900 GRAPEVINE ST  HOUSTON    TX

[353181 rows x 4 columns]

In [60]:
geo_df.to_csv('geo_csv.csv')

In [63]:
import censusgeocode as cg
import time
from random_words import RandomWords
import math

rw = RandomWords()

df_names = rw.random_words(count=100)

k_list = []

mylist = list(range(math.ceil(50000/500)))
# print(mylist)

# increments = [geo_df[0:20], geo_df[5000:9999], geo_df[10000:14999], geo_df[15000:19999], geo_df[20000:24999], geo_df[25000:29999], geo_df[30000:39999], geo_df[40000:44999], geo_df[45000:49999], geo_df[50000:54999], geo_df[550000:59999], geo_df[60000:64999], geo_df[65000:69999], geo_df[70000:74999], geo_df[75000:79999], geo_df[80000:84999], geo_df[85000:89999], geo_df[90000:94999], geo_df[95000:99999], geo_df[100000:104999], geo_df[105000:109999], geo_df[110000:114999], geo_df[1150000:119999], geo_df[120000:124999], geo_df[125000:129999], geo_df[130000:134999], geo_df[135000:139999], geo_df[140000:144999], geo_df[145000:149000], geo_df[150000:154999], geo_df[155000:159999], geo_df[160000:164999], geo_df[165000:169999], geo_df[170000:174999], geo_df[175000:179999], geo_df[180000:184999], geo_df[185000:189999], geo_df[190000:194999], geo_df[195000:199999], geo_df[200000:204999], geo_df[205000:209999], geo_df[210000:214999], geo_df[2150000:219999], geo_df[220000:224999], geo_df[225000:229999], geo_df[230000:234999], geo_df[235000:239999], geo_df[240000:244999], geo_df[245000:249000], geo_df[250000:254999], geo_df[255000:259999], geo_df[260000:264999], geo_df[265000:269999], geo_df[270000:274999], geo_df[275000:279999], geo_df[280000:284999], geo_df[285000:289999], geo_df[290000:294999], geo_df[295000:299999], geo_df[300000:304999], geo_df[305000:309999], geo_df[310000:314999], geo_df[3150000:319999], geo_df[320000:324999], geo_df[325000:329999], geo_df[330000:334999], geo_df[335000:339999], geo_df[340000:344999], geo_df[345000:349000], geo_df[350000:354999], geo_df[355000:359999], geo_df[360000:364999], geo_df[365000:369999], geo_df[370000:374999], geo_df[375000:379999], geo_df[380000:384999], geo_df[385000:389999], geo_df[390000:394999], geo_df[395000:399999], geo_df[400000:404999], geo_df[405000:409999], geo_df[410000:414999], geo_df[4150000:419999], geo_df[420000:424999], geo_df[425000:429999], geo_df[430000:434999], geo_df[435000:439999], geo_df[440000:444999], geo_df[445000:449000], geo_df[450000:454999], geo_df[455000:459999], geo_df[460000:464999], geo_df[465000:469999], geo_df[470000:474999], geo_df[475000:479999], geo_df[480000:484999], geo_df[485000:489999], geo_df[490000:494999], geo_df[495000:]]
counter = 0
start = 0
end = 499

for items in mylist:
    geo_df[start:end].to_csv(f'crime{counter}.csv', header=False)
    k = cg.addressbatch(f'crime{counter}.csv')
    k_list.append(k)
    if counter == 0:
        df_names[int(f'{counter}')] = pd.DataFrame(k, columns=k[0].keys())
    if counter > 0:
        df_names[int(f'{counter}')] = pd.DataFrame(k, columns=k[0].keys())
        df_names[int(f'{counter}')] = pd.concat([df_names[counter-1], df_names[counter]])
        final_locations = (df_names[int(f'{counter}')])
    print(counter)
    counter+=1
    start += 500
    end += 500
    time.sleep(30)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
0
1
2
3

ConnectionError: ('Connection aborted.', OSError("(54, 'ECONNRESET')"))

In [37]:
final_locations['id'] = final_locations['id'].astype(int)
final_locations.sort_values(by='id').head(50)

,id,address,match,matchtype,parsed,tigerlineid,side,statefp,countyfp,tract,block,lat,lon
8,0,"9311 BELLA PINE CT, HOUSTON, TX,",True,Exact,"9311 BELLA PINE CT, HOUSTON, TX, 77078",96424184,R,48,201,231200,3000,29.856209,-95.252335
9,1,"8701 GUSTINE LN, HOUSTON, TX,",True,Exact,"8701 GUSTINE LN, HOUSTON, TX, 77031",96598570,L,48,201,423202,1004,29.669638,-95.530464
10,2,"8064 LENORE , HOUSTON, TX,",True,Non_Exact,"8064 LENORE ST, HOUSTON, TX, 77017",96606137,R,48,201,320602,3014,29.676530,-95.263540
11,3,"5930 DASHWOOD DR, HOUSTON, TX,",True,Exact,"5930 DASHWOOD DR, HOUSTON, TX, 77081",642048438,R,48,201,421403,3011,29.707360,-95.485760
12,4,"5218 KENILWOOD DR, HOUSTON, TX,",True,Exact,"5218 KENILWOOD DR, HOUSTON, TX, 77033",629130964,R,48,201,332000,1015,29.672613,-95.344020
13,5,"2851 WALLINGFORD DR, HOUSTON, TX,",True,Exact,"2851 WALLINGFORD DR, HOUSTON, TX, 77042",96619380,R,48,201,452201,1007,29.732517,-95.563830
14,6,"16410 SKEET CT, HOUSTON, TX,",False,None,None,None,None,None,None,None,None,NaN,NaN
15,7,"400 80TH ST, HOUSTON, TX,",True,Exact,"400 80TH ST, HOUSTON, TX, 77012",96085219,R,48,201,311100,4031,29.731415,-95.281470
16,8,"2434 LIDSTONE , HOUSTON, TX,",True,Non_Exact,"2434 LIDSTONE ST, HOUSTON, TX, 77023",96082628,R,48,201,311900,2053,29.715660,-95.321650
17,9,"8115 PENROD , HOUSTON, TX,",True,Non_Exact,"8115 PENROD ST, HOUSTON, TX, 77028",96077894,L,48,201,230900,1013,29.825815,-95.278270
18,10,"16214 LAZY RIDGE DR, HOUSTON, TX,",True,Non_Exact,"16214 LAZY RIDGE RD, HOUSTON, TX, 77053",78271887,L,48,157,670101,3024,29.586360,-95.455780
0,12,"3588 OCEE ST, HOUSTON, TX,",True,Exact,"3588 OCEE ST, HOUSTON, TX, 77063",96614289,R,48,201,432500,2006,29.724594,-95.529110
1,13,"5425 NIELAN , HOUSTON, TX,",True,Non_Exact,"5425 NIELAN ST, HOUSTON, TX, 77028",96078198,L,48,201,230900,3057,29.810284,-95.279200
2,14,"228 ALTIC ST, HOUSTON, TX,",True,Exact,"228 ALTIC ST, HOUSTON, TX, 77011",96565782,R,48,201,310500,2014,29.743021,-95.319760
3,15,"502 RAINY MEADOW LN, HOUSTON, TX,",True,Exact,"502 RAINY MEADOW LN, HOUSTON, TX, 77013",96084777,R,48,201,232600,2006,29.780453,-95.241540
4,16,"10800 BISSONNET ST, HOUSTON, TX,",True,Exact,"10800 BISSONNET ST, HOUSTON, TX, 77099",641840301,R,48,201,453200,1052,29.674140,-95.568700
5,17,"9410 RICHMOND AVE, HOUSTON, TX,",True,Non_Exact,"9410 S RICHMOND AVE, HOUSTON, TX, 77082",636879734,L,48,201,454301,3025,29.726767,-95.650850
6,18,"6429 DAWNRIDGE DR, HOUSTON, TX,",True,Exact,"6429 DAWNRIDGE DR, HOUSTON, TX, 77035",96595524,L,48,201,422301,3001,29.648577,-95.503890
7,19,"6422 BROOKLAWN DR, HOUSTON, TX,",True,Exact,"6422 BROOKLAWN DR, HOUSTON, TX, 77085",96040644,R,48,201,330302,1012,29.608540,-95.480804
17,21,"16302 EL CAMINO REAL , HOUSTON, TX,",True,Exact,"16302 EL CAMINO REAL, HOUSTON, TX, 77062",96590045,R,48,201,340700,3015,29.560070,-95.125175
0,22,"4100 SOUTHWEST FWY, HOUSTON, TX,",True,Exact,"4100 SOUTHWEST FWY, HOUSTON, TX, 77027",639331301,R,48,201,411501,1008,29.729618,-95.444520
2,23,"1300 GEMINI AVE, HOUSTON, TX,",True,Non_Exact,"1300 GEMINI ST, HOUSTON, TX, 77058",96115836,R,48,201,341302,2001,29.558006,-95.113000
4,24,"900 LAKESIDE ESTATES DR, HOUSTON, TX,",False,None,None,None,None,None,None,None,None,NaN,NaN
6,25,"12610 HUNTING BROOK DR, HOUSTON, TX,",True,Exact,"12610 HUNTING BROOK DR, HOUSTON, TX, 77099",96035582,R,48,201,453800,2001,29.668790,-95.606530
8,26,"14711 MAIN ST, HOUSTON, TX,",False,None,None,None,None,None,None,None,None,NaN,NaN
10,27,"11907 SANDPIPER DR, HOUSTON, TX,",True,Exact,"11907 SANDPIPER DR, HOUSTON, TX, 77035",96038101,R,48,201,422301,2008,29.648903,-95.503190
12,28,"3030 SHADOWBRIAR DR, HOUSTON, TX,",True,Exact,"3030 SHADOWBRIAR DR, HOUSTON, TX, 77082",641738033,L,48,201,452000,3013,29.731070,-95.599800
14,29,"3030 SHADOWBRIAR DR, HOUSTON, TX,",True,Exact,"3030 SHADOWBRIAR DR, HOUSTON, TX, 77082",641738033,L,48,201,452000,3013,29.731070,-95.599800
15,30,"3449 TAMPA ST, HOUSTON, TX,",True,Exact,"3449 TAMPA ST, HOUSTON, TX, 77021",96072543,L,48,201,313200,3016,29.704666,-95.366960
16,31,"9850 PAGEWOOD LN, HOUSTON, TX,",True,Exact,"9850 PAGEWOOD LN, HOUSTON, TX, 77042",96613910,R,48,201,432400,3002,29.725391,-95.542270
18,32,"3357 LINN , HOUSTON, TX,",True,Non_Exact,"3357 LINN ST, HOUSTON, TX, 77026",640073390,L,48,201,211100,2003,29.792640,-95.335915
1,33,"2440 FIRNAT , HOUSTON, TX,",True,Non_Exact,"2440 FIRNAT ST, HOUSTON, TX, 77093",96644134,R,48,201,220700,1007,29.842297,-95.347150
3,34,"7503 ANTOINE DR, HOUSTON, TX,",True,Exact,"7503 ANTOINE DR, HOUSTON, TX, 77088",96027044,L,48,201,532700,3007,29.871193,-95.473520
5,35,"8010 LINDA VISTA RD, HOUSTON, TX,",True,Exact,"8010 LINDA VISTA RD, HOUSTON, TX, 77028",96077795,R,48,201,231000,2026,29.838797,-95.282190
7,36,"116 EDGEBROOK DR, HOUSTON, TX,",True,Exact,"116 EDGEBROOK DR, HOUSTON, TX, 77034",96596822,L,48,201,321000,1001,29.647259,-95.221725
9,37,"116 EDGEBROOK DR, HOUSTON, TX,",True,Exact,"116 EDGEBROOK DR, HOUSTON, TX, 77034",96596822,L,48,201,321000,1001,29.647259,-95.221725
11,38,"7038 DILLON ST, HOUSTON, TX,",True,Exact,"7038 DILLON ST, HOUSTON, TX, 77061",96092252,R,48,201,333600,2013,29.653930,-95.303390
13,39,"3125 CRESTDALE DR, HOUSTON, TX,",True,Exact,"3125 CRESTDALE DR, HOUSTON, TX, 77080",96639062,L,48,201,522100,3008,29.819866,-95.530640
12,41,"8779 BELLFORT AVE, HOUSTON, TX,",False,None,None,None,None,None,None,None,None,NaN,NaN
14,42,"6038 BEEKMAN RD, HOUSTON, TX,",True,Exact,"6038 BEEKMAN RD, HOUSTON, TX, 77021",96090868,R,48,201,313400,2026,29.692950,-95.332980
17,43,"6038 BEEKMAN RD, HOUSTON, TX,",True,Exact,"6038 BEEKMAN RD, HOUSTON, TX, 77021",96090868,R,48,201,313400,2026,29.692950,-95.332980
0,44,"322 PARLIAMENT DR, HOUSTON, TX,",True,Exact,"322 PARLIAMENT DR, HOUSTON, TX, 77034",96103835,R,48,201,321300,3018,29.645418,-95.210520
2,45,"5502 THRUSH DR, HOUSTON, TX,",True,Exact,"5502 THRUSH DR, HOUSTON, TX, 77033",96089996,R,48,201,331900,3008,29.659903,-95.341410
4,47,"8721 TOWN PARK DR, HOUSTON, TX,",True,Exact,"8721 TOWN PARK DR, HOUSTON, TX, 77036",96613760,L,48,201,433002,2000,29.713953,-95.541626
7,49,"3026 OAKDALE ST, HOUSTON, TX,",True,Exact,"3026 OAKDALE ST, HOUSTON, TX, 77004",96072394,R,48,201,313000,2002,29.717360,-95.370410
9,50,"10002 SOUTHWEST FWY, HOUSTON, TX,",True,Exact,"10002 SOUTHWEST FWY, HOUSTON, TX, 77074",96149919,L,48,201,433600,3044,29.670584,-95.548220
11,51,"10306 BLADES ST, HOUSTON, TX,",True,Exact,"10306 BLADES ST, HOUSTON, TX, 77016",96075677,R,48,201,231500,1015,29.862406,-95.294950
13,52,"12300 HODGES ST, HOUSTON, TX,",True,Exact,"12300 HODGES ST, HOUSTON, TX, 77085",640073314,R,48,201,330303,1034,29.629095,-95.503480
15,53,"3000 SH 6 , HOUSTON, TX,",False,None,None,None,None,None,None,None,None,NaN,NaN
18,54,"3560 DIXIE DR, HOUSTON, TX,",True,Exact,"3560 DIXIE DR, HOUSTON, TX, 77021",96072552,R,48,201,313200,3021,29.703170,-95.366264

In [58]:
# This works, but doesn't give census tract at all

# import requests
# import csv
# import re

# def censusGeocode(file, output):
#     url = 'https://geocoding.geo.census.gov/geocoder/locations/addressbatch?form'
#     payload = {'benchmark':'Public_AR_Current', 'vintage':'Current_Current',}
#     files = {'addressFile': open(file)}
#     r = requests.post(url, files=files, data=payload)
#     results = str(r.text)
#     results = re.sub('"','',results)
#     results = results.split('\n')
#     with open(output, 'w', newline = '') as geocodeOutput:
#         w = csv.writer(geocodeOutput, delimiter=',')
#         w.writerows([c.strip() for c in r.split(',')] for r in results)
# censusGeocode('geo_csv_test.csv', 'geo_test_results.csv')

In [55]:
# geo_test_df = pd.read_csv('geo_test_results.csv')
# geo_test_df

,,,,,,,,,Unnamed: 0,Street_Address,City,State,Zip_Code,No_Match
88.0,2416 BRAZOS ST,HOUSTON,TX,NaN,Match,Exact,2416 BRAZOS ST,HOUSTON,TX,77006.0,-95.377556,29.749035,96067126.0,R
89.0,4400 HWY 225,HOUSTON,TX,NaN,No_Match,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110.0,4250 34TH ST,HOUSTON,TX,NaN,Match,Non_Exact,4250 W 34TH ST,HOUSTON,TX,77092.0,-95.451996,29.817581,644872532.0,R
111.0,11943 BISSONNET ST,HOUSTON,TX,NaN,No_Match,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90.0,16826 CITY VIEW PL,HOUSTON,TX,NaN,No_Match,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109.0,8115 NELLIE,HOUSTON,TX,NaN,Match,Non_Exact,8115 NELLIE ST,HOUSTON,TX,77022.0,-95.359980,29.835060,96553836.0,L
83.0,2110 BALDWIN ST,HOUSTON,TX,NaN,Match,Exact,2110 BALDWIN ST,HOUSTON,TX,77002.0,-95.377540,29.752249,96067106.0,R
84.0,2404 SAN JACINTO ST,HOUSTON,TX,NaN,Match,Exact,2404 SAN JACINTO ST,HOUSTON,TX,77002.0,-95.371630,29.745262,96071438.0,R
87.0,8410 BARTELL DR,HOUSTON,TX,NaN,No_Match,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN