In [1]:
import pandas as pd

In [3]:
lat_lngs = ["LatLng1.csv", 
            "LatLng2.csv",
            "LatLng3.csv",
            "LatLng4.csv",
            "LatLng5.csv",
            "LatLng6.csv",
            "LatLng7.csv",
            "LatLng8.csv",]

li = []

for csv in lat_lngs:
    df = pd.read_csv(csv, index_col=None, header=0)
    li.append(df)

full_lat_lngs = pd.concat(li, axis=0, ignore_index=True)

full_lat_lngs

         Latitude  Longitude
0       29.856285 -95.251628
1       29.669442 -95.532628
2       29.676495 -95.263450
3       29.707437 -95.485750
4       29.672524 -95.344034
...           ...        ...
406479  29.735983 -95.286111
406480  29.685652 -95.355172
406481  29.608823 -95.255404
406482        NaN        NaN
406483  29.616695 -95.435411

[406484 rows x 2 columns]

In [5]:
crime_df = pd.read_csv('revised_crimes_geo.csv')

crime_df

/Users/ryanashcraft/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address,Zip_Code,Full_Address
0,0,1/1/20,0.0,Theft,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,Houston,TX,9311+BELLA+PINE+CT,NaN,"9311 BELLA PINE CT, Houston, TX"
1,1,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,Houston,TX,8701+GUSTINE+LN,NaN,"8701 GUSTINE LN, Houston, TX"
2,2,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",8064,LENORE,NaN,Houston,TX,8064+LENORE+,NaN,"8064 LENORE , Houston, TX"
3,3,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,Houston,TX,5930+DASHWOOD+DR,NaN,"5930 DASHWOOD DR, Houston, TX"
4,4,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,Houston,TX,5218+KENILWOOD+DR,NaN,"5218 KENILWOOD DR, Houston, TX"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406479,498669,12/31/18,23.0,Vandalism,1.0,"Church, Synagogue, Temple",7700,AVENUE H,NaN,Houston,TX,7700+AVENUE+H+,NaN,"7700 AVENUE H , Houston, TX"
406480,498670,12/31/18,23.0,Intimidation,1.0,"Service, Gas Station",7100,CULLEN,BLVD,Houston,TX,7100+CULLEN+BLVD,NaN,"7100 CULLEN BLVD, Houston, TX"
406481,498671,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",10800,QUILL GARDEN,LN,Houston,TX,10800+QUILL+GARDEN+LN,NaN,"10800 QUILL GARDEN LN, Houston, TX"
406482,498672,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",16300,COVEY RUN,DR,Houston,TX,16300+COVEY+RUN+DR,NaN,"16300 COVEY RUN DR, Houston, TX"
406483,498676,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,Houston,TX,3900+GRAPEVINE+ST,NaN,"3900 GRAPEVINE ST, Houston, TX"

In [6]:
crime_df['Latitude'] = full_lat_lngs['Latitude']

crime_df

,Unnamed: 0,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address,Zip_Code,Full_Address,Latitude
0,0,1/1/20,0.0,Theft,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,Houston,TX,9311+BELLA+PINE+CT,NaN,"9311 BELLA PINE CT, Houston, TX",29.856285
1,1,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,Houston,TX,8701+GUSTINE+LN,NaN,"8701 GUSTINE LN, Houston, TX",29.669442
2,2,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",8064,LENORE,NaN,Houston,TX,8064+LENORE+,NaN,"8064 LENORE , Houston, TX",29.676495
3,3,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,Houston,TX,5930+DASHWOOD+DR,NaN,"5930 DASHWOOD DR, Houston, TX",29.707437
4,4,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,Houston,TX,5218+KENILWOOD+DR,NaN,"5218 KENILWOOD DR, Houston, TX",29.672524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406479,498669,12/31/18,23.0,Vandalism,1.0,"Church, Synagogue, Temple",7700,AVENUE H,NaN,Houston,TX,7700+AVENUE+H+,NaN,"7700 AVENUE H , Houston, TX",29.735983
406480,498670,12/31/18,23.0,Intimidation,1.0,"Service, Gas Station",7100,CULLEN,BLVD,Houston,TX,7100+CULLEN+BLVD,NaN,"7100 CULLEN BLVD, Houston, TX",29.685652
406481,498671,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",10800,QUILL GARDEN,LN,Houston,TX,10800+QUILL+GARDEN+LN,NaN,"10800 QUILL GARDEN LN, Houston, TX",29.608823
406482,498672,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",16300,COVEY RUN,DR,Houston,TX,16300+COVEY+RUN+DR,NaN,"16300 COVEY RUN DR, Houston, TX",NaN
406483,498676,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,Houston,TX,3900+GRAPEVINE+ST,NaN,"3900 GRAPEVINE ST, Houston, TX",29.616695

In [7]:
crime_df['Longitude'] = full_lat_lngs['Longitude']

crime_df

,Unnamed: 0,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address,Zip_Code,Full_Address,Latitude,Longitude
0,0,1/1/20,0.0,Theft,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,Houston,TX,9311+BELLA+PINE+CT,NaN,"9311 BELLA PINE CT, Houston, TX",29.856285,-95.251628
1,1,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,Houston,TX,8701+GUSTINE+LN,NaN,"8701 GUSTINE LN, Houston, TX",29.669442,-95.532628
2,2,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",8064,LENORE,NaN,Houston,TX,8064+LENORE+,NaN,"8064 LENORE , Houston, TX",29.676495,-95.263450
3,3,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,Houston,TX,5930+DASHWOOD+DR,NaN,"5930 DASHWOOD DR, Houston, TX",29.707437,-95.485750
4,4,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,Houston,TX,5218+KENILWOOD+DR,NaN,"5218 KENILWOOD DR, Houston, TX",29.672524,-95.344034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406479,498669,12/31/18,23.0,Vandalism,1.0,"Church, Synagogue, Temple",7700,AVENUE H,NaN,Houston,TX,7700+AVENUE+H+,NaN,"7700 AVENUE H , Houston, TX",29.735983,-95.286111
406480,498670,12/31/18,23.0,Intimidation,1.0,"Service, Gas Station",7100,CULLEN,BLVD,Houston,TX,7100+CULLEN+BLVD,NaN,"7100 CULLEN BLVD, Houston, TX",29.685652,-95.355172
406481,498671,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",10800,QUILL GARDEN,LN,Houston,TX,10800+QUILL+GARDEN+LN,NaN,"10800 QUILL GARDEN LN, Houston, TX",29.608823,-95.255404
406482,498672,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",16300,COVEY RUN,DR,Houston,TX,16300+COVEY+RUN+DR,NaN,"16300 COVEY RUN DR, Houston, TX",NaN,NaN
406483,498676,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,Houston,TX,3900+GRAPEVINE+ST,NaN,"3900 GRAPEVINE ST, Houston, TX",29.616695,-95.435411

In [8]:
census_csvs = ["census1.csv", 
            "census2.csv",
           "census3.csv",
           "census4.csv",
           "census5.csv",
           "census6.csv",
           "census7.csv",
           "census8a.csv",
           "census8b.csv",
           "census8c.csv",
           "census8d.csv",
           "census8e.csv",
           "census8f.csv",]

li = []

for csv in census_csvs:
    df = pd.read_csv(csv, index_col=None, header=0)
    li.append(df)

tract_df = pd.concat(li, axis=0, ignore_index=True)

tract_df

        Census_Tract
0           231200.0
1           423202.0
2           320602.0
3           421403.0
4           332000.0
...              ...
406479      311100.0
406480      313600.0
406481      333901.0
406482           NaN
406483      330600.0

[406484 rows x 1 columns]

In [10]:
crime_df['Tract'] = tract_df['Census_Tract']

crime_df

,Unnamed: 0,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,Street_Address,Zip_Code,Full_Address,Latitude,Longitude,Tract
0,0,1/1/20,0.0,Theft,1.0,"Residence, Home (Includes Apartment)",9311,BELLA PINE,CT,Houston,TX,9311+BELLA+PINE+CT,NaN,"9311 BELLA PINE CT, Houston, TX",29.856285,-95.251628,231200.0
1,1,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",8701,GUSTINE,LN,Houston,TX,8701+GUSTINE+LN,NaN,"8701 GUSTINE LN, Houston, TX",29.669442,-95.532628,423202.0
2,2,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",8064,LENORE,NaN,Houston,TX,8064+LENORE+,NaN,"8064 LENORE , Houston, TX",29.676495,-95.263450,320602.0
3,3,1/1/20,0.0,Assault,1.0,"Residence, Home (Includes Apartment)",5930,DASHWOOD,DR,Houston,TX,5930+DASHWOOD+DR,NaN,"5930 DASHWOOD DR, Houston, TX",29.707437,-95.485750,421403.0
4,4,1/1/20,0.0,Vandalism,1.0,"Residence, Home (Includes Apartment)",5218,KENILWOOD,DR,Houston,TX,5218+KENILWOOD+DR,NaN,"5218 KENILWOOD DR, Houston, TX",29.672524,-95.344034,332000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406479,498669,12/31/18,23.0,Vandalism,1.0,"Church, Synagogue, Temple",7700,AVENUE H,NaN,Houston,TX,7700+AVENUE+H+,NaN,"7700 AVENUE H , Houston, TX",29.735983,-95.286111,311100.0
406480,498670,12/31/18,23.0,Intimidation,1.0,"Service, Gas Station",7100,CULLEN,BLVD,Houston,TX,7100+CULLEN+BLVD,NaN,"7100 CULLEN BLVD, Houston, TX",29.685652,-95.355172,313600.0
406481,498671,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",10800,QUILL GARDEN,LN,Houston,TX,10800+QUILL+GARDEN+LN,NaN,"10800 QUILL GARDEN LN, Houston, TX",29.608823,-95.255404,333901.0
406482,498672,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",16300,COVEY RUN,DR,Houston,TX,16300+COVEY+RUN+DR,NaN,"16300 COVEY RUN DR, Houston, TX",NaN,NaN,NaN
406483,498676,12/31/18,23.0,Assault,1.0,"Residence, Home (Includes Apartment)",3900,GRAPEVINE,ST,Houston,TX,3900+GRAPEVINE+ST,NaN,"3900 GRAPEVINE ST, Houston, TX",29.616695,-95.435411,330600.0

In [ ]:
crime_df.to_csv('Full_Crimes_CSV.csv')