In [1]:
import pandas as pd

In [2]:
data_csvs = ["1. final_dataset(0-200000).csv", 
            "2. final_dataset(200000-up).csv"]

li = []

for csv in data_csvs:
    data_df = pd.read_csv(csv, index_col=0, header=0)
    li.append(data_df)

full_data = pd.concat(li, axis=0, ignore_index=True)

full_data

/Users/ryanashcraft/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,...,Day,Week_Num,Day_of_Week,Temperature,Precipitation,Weather,Weather_Description,Total_Popupation,Total_Households,Median_Household_Income
0,01/01/2018,0,Burglary/Robbery,1.0,Residence or House,1300,ROSEDALE,ST,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,3561.0,1836.0,85531.0
1,01/01/2018,0,Burglary/Robbery,1.0,Apartment,3900,ARLINGTON SQUARE DR,-,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,7091.0,2090.0,43452.0
2,01/01/2018,0,Burglary/Robbery,1.0,"Road, Street, or Sidewalk",7200,BELLERIVE DRIVE,-,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,5059.0,2062.0,36309.0
3,01/01/2018,0,Assault,2.0,"Road, Street, or Sidewalk",4900,DANFIELD,-,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,9909.0,2479.0,49702.0
4,01/01/2018,0,Theft,1.0,"Church, Synagogue, or Temple Parking Lot",3100,CLEBURNE,ST,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,2514.0,663.0,12260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453199,9/9/19,23,Burglary/Robbery,1.0,"Residence, Home (Includes Apartment)",2555,BERING,DR,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,3470.0,2106.0,86133.0
453200,9/9/19,23,Theft,1.0,"Residence, Home (Includes Apartment)",2555,BERING,DR,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,3470.0,2106.0,86133.0
453201,9/9/19,23,Burglary/Robbery,1.0,"Commercial, Office Building",8499,GULF,FWY,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,4835.0,1458.0,41143.0
453202,9/9/19,23,Assault,1.0,"Parking Lot, Garage",2434,LIDSTONE,NaN,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,2600.0,712.0,43295.0
453203,9/9/19,23,Theft,1.0,"Parking Lot, Garage",8215,KOPMAN,DR,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,NaN,NaN,NaN

In [3]:
counts = full_data['Tract'].value_counts()

full_data = full_data[~full_data['Tract'].isin(counts[counts < 2].index)]

full_data

,Date,Hour,Offense_Type,Offense_Count,Premise,Block_Range,Street_Name,Street_Type,City,State,...,Day,Week_Num,Day_of_Week,Temperature,Precipitation,Weather,Weather_Description,Total_Popupation,Total_Households,Median_Household_Income
0,01/01/2018,0,Burglary/Robbery,1.0,Residence or House,1300,ROSEDALE,ST,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,3561.0,1836.0,85531.0
1,01/01/2018,0,Burglary/Robbery,1.0,Apartment,3900,ARLINGTON SQUARE DR,-,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,7091.0,2090.0,43452.0
2,01/01/2018,0,Burglary/Robbery,1.0,"Road, Street, or Sidewalk",7200,BELLERIVE DRIVE,-,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,5059.0,2062.0,36309.0
3,01/01/2018,0,Assault,2.0,"Road, Street, or Sidewalk",4900,DANFIELD,-,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,9909.0,2479.0,49702.0
4,01/01/2018,0,Theft,1.0,"Church, Synagogue, or Temple Parking Lot",3100,CLEBURNE,ST,Houston,TX,...,1,1.0,Monday,46.56,0.0,Clouds,overcast clouds,2514.0,663.0,12260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453199,9/9/19,23,Burglary/Robbery,1.0,"Residence, Home (Includes Apartment)",2555,BERING,DR,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,3470.0,2106.0,86133.0
453200,9/9/19,23,Theft,1.0,"Residence, Home (Includes Apartment)",2555,BERING,DR,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,3470.0,2106.0,86133.0
453201,9/9/19,23,Burglary/Robbery,1.0,"Commercial, Office Building",8499,GULF,FWY,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,4835.0,1458.0,41143.0
453202,9/9/19,23,Assault,1.0,"Parking Lot, Garage",2434,LIDSTONE,NaN,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,2600.0,712.0,43295.0
453203,9/9/19,23,Theft,1.0,"Parking Lot, Garage",8215,KOPMAN,DR,Houston,TX,...,9,37.0,Monday,90.34,0.0,Clear,sky is clear,NaN,NaN,NaN

In [4]:
small_df = full_data.dropna()

small_df['Tract'].value_counts()

980000.0    17424
100000.0     5826
410600.0     3558
312500.0     3402
431900.0     3325
            ...
222200.0        1
551900.0        1
552002.0        1
454000.0        1
672602.0        1
Name: Tract, Length: 606, dtype: int64

In [13]:
small_df['Date'].unique()

array(['01/01/2018', '01/02/2018', '01/03/2018', '01/04/2018',
       '01/05/2018', '01/06/2018', '01/07/2018', '01/08/2018',
       '01/09/2018', '01/10/2018', '01/11/2018', '01/12/2018',
       '01/13/2018', '01/14/2018', '01/15/2018', '01/16/2018',
       '01/17/2018', '01/18/2018', '01/19/2018', '01/20/2018',
       '01/21/2018', '01/22/2018', '01/23/2018', '01/24/2018',
       '01/25/2018', '01/26/2018', '01/27/2018', '01/28/2018',
       '01/29/2018', '01/30/2018', '01/31/2018', '02/01/2018',
       '02/02/2018', '02/03/2018', '02/04/2018', '02/05/2018',
       '02/06/2018', '02/07/2018', '02/08/2018', '02/09/2018',
       '02/10/2018', '02/11/2018', '02/12/2018', '02/13/2018',
       '02/14/2018', '02/15/2018', '02/16/2018', '02/17/2018',
       '02/18/2018', '02/19/2018', '02/20/2018', '02/21/2018',
       '02/22/2018', '02/23/2018', '02/24/2018', '02/25/2018',
       '02/26/2018', '02/27/2018', '02/28/2018', '03/01/2018',
       '03/02/2018', '03/03/2018', '03/04/2018', '03/05/2018',
       '03/06/2018', '03/07/2018', '03/08/2018', '03/09/2018',
       '03/10/2018', '03/11/2018', '03/12/2018', '03/13/2018',
       '03/14/2018', '03/15/2018', '03/16/2018', '03/17/2018',
       '03/18/2018', '03/19/2018', '03/20/2018', '03/21/2018',
       '03/22/2018', '03/23/2018', '03/24/2018', '03/25/2018',
       '03/26/2018', '03/27/2018', '03/28/2018', '03/29/2018',
       '03/30/2018', '03/31/2018', '04/01/2018', '04/02/2018',
       '04/03/2018', '04/04/2018', '04/05/2018', '04/06/2018',
       '04/07/2018', '04/08/2018', '04/09/2018', '04/10/2018',
       '04/11/2018', '04/12/2018', '04/13/2018', '04/14/2018',
       '04/15/2018', '04/16/2018', '04/17/2018', '04/18/2018',
       '04/19/2018', '04/20/2018', '04/21/2018', '04/22/2018',
       '04/23/2018', '04/24/2018', '04/25/2018', '04/26/2018',
       '04/27/2018', '04/28/2018', '04/29/2018', '04/30/2018',
       '05/01/2018', '05/02/2018', '05/03/2018', '05/04/2018',
       '05/05/2018', '05/06/2018', '05/07/2018', '05/08/2018',
       '05/09/2018', '05/10/2018', '05/11/2018', '05/12/2018',
       '05/13/2018', '05/14/2018', '05/15/2018', '05/16/2018',
       '05/17/2018', '05/18/2018', '05/19/2018', '05/20/2018',
       '05/21/2018', '05/22/2018', '05/23/2018', '05/24/2018',
       '05/25/2018', '05/26/2018', '05/27/2018', '05/28/2018',
       '05/29/2018', '05/30/2018', '05/31/2018', '1/1/19', '1/1/20',
       '1/10/19', '1/10/20', '1/11/19', '1/11/20', '1/12/19', '1/12/20',
       '1/13/19', '1/13/20', '1/14/19', '1/14/20', '1/15/19', '1/15/20',
       '1/16/19', '1/16/20', '1/17/19', '1/17/20', '1/18/19', '1/18/20',
       '1/19/19', '1/19/20', '1/2/19', '1/2/20', '1/20/19', '1/20/20',
       '1/21/19', '1/21/20', '1/22/19', '1/22/20', '1/23/19', '1/23/20',
       '1/24/19', '1/24/20', '1/25/19', '1/25/20', '1/26/19', '1/26/20',
       '1/27/19', '1/27/20', '1/28/19', '1/28/20', '1/29/19', '1/29/20',
       '1/3/19', '1/3/20', '1/30/19', '1/30/20', '1/31/19', '1/31/20',
       '1/4/19', '1/4/20', '1/5/19', '1/5/20', '1/6/19', '1/6/20',
       '1/7/19', '1/7/20', '1/8/19', '1/8/20', '1/9/19', '1/9/20',
       '10/1/18', '10/1/19', '10/10/18', '10/10/19', '10/11/18',
       '10/11/19', '10/12/18', '10/12/19', '10/13/18', '10/13/19',
       '10/14/18', '10/14/19', '10/15/18', '10/15/19', '10/16/18',
       '10/16/19', '10/17/18', '10/17/19', '10/18/18', '10/18/19',
       '10/19/18', '10/19/19', '10/2/18', '10/2/19', '10/20/18',
       '10/20/19', '10/21/18', '10/21/19', '10/22/18', '10/22/19',
       '10/23/18', '10/23/19', '10/24/18', '10/24/19', '10/25/18',
       '10/25/19', '10/26/18', '10/26/19', '10/27/18', '10/27/19',
       '10/28/18', '10/28/19', '10/29/18', '10/29/19', '10/3/18',
       '10/3/19', '10/30/18', '10/30/19', '10/31/18', '10/31/19',
       '10/4/18', '10/4/19', '10/5/18', '10/5/19', '10/6/18', '10/6/19',
       '10/7/18', '10/7/19', '10/8/18', '10/8/19', '10/9/18', '10/9/19',
       '11/1/18', '11/1/19', '11/10/18', '11/10/19', '11/11/18',
       '11/11/19', '11/12/18', '11/12/19', '11/13/18', '11/13/19',
       '11/14/18', '11/14/19', '11/15/18', '11/15/19', '11/16/18',
       '11/16/19', '11/17/18', '11/17/19', '11/18/18', '11/18/19',
       '11/19/18', '11/19/19', '11/2/18', '11/2/19', '11/20/18',
       '11/20/19', '11/21/18', '11/21/19', '11/22/18', '11/22/19',
       '11/23/18', '11/23/19', '11/24/18', '11/24/19', '11/25/18',
       '11/25/19', '11/26/18', '11/26/19', '11/27/18', '11/27/19',
       '11/28/18', '11/28/19', '11/29/18', '11/29/19', '11/3/18',
       '11/3/19', '11/30/18', '11/30/19', '11/4/18', '11/4/19', '11/5/18',
       '11/5/19', '11/6/18', '11/6/19', '11/7/18', '11/7/19', '11/8/18',
       '11/8/19', '11/9/18', '11/9/19', '12/1/18', '12/1/19', '12/10/18',
       '12/10/19', '12/11/18', '12/11/19', '12/12/18', '12/12/19',
       '12/13/18', '12/13/19', '12/14/18', '12/14/19', '12/15/18',
       '12/15/19', '12/16/18', '12/16/19', '12/17/18', '12/17/19',
       '12/18/18', '12/18/19', '12/19/18', '12/19/19', '12/2/18',
       '12/2/19', '12/20/18', '12/20/19', '12/21/18', '12/21/19',
       '12/22/18', '12/22/19', '12/23/18', '12/23/19', '12/24/18',
       '12/24/19', '12/25/18', '12/25/19', '12/26/18', '12/26/19',
       '12/27/18', '12/27/19', '12/28/18', '12/28/19', '12/29/18',
       '12/29/19', '12/3/18', '12/3/19', '12/30/18', '12/30/19',
       '12/31/18', '12/31/19', '12/4/18', '12/4/19', '12/5/18', '12/5/19',
       '12/6/18', '12/6/19', '12/7/18', '12/7/19', '12/8/18', '12/8/19',
       '12/9/18', '12/9/19', '2/1/19', '2/1/20', '2/10/19', '2/10/20',
       '2/11/19', '2/11/20', '2/12/19', '2/12/20', '2/13/19', '2/13/20',
       '2/14/19', '2/14/20', '2/15/19', '2/15/20', '2/16/19', '2/16/20',
       '2/17/19', '2/17/20', '2/18/19', '2/18/20', '2/19/19', '2/19/20',
       '2/2/19', '2/2/20', '2/20/19', '2/20/20', '2/21/19', '2/21/20',
       '2/22/19', '2/22/20', '2/23/19', '2/23/20', '2/24/19', '2/24/20',
       '2/25/19', '2/25/20', '2/26/19', '2/26/20', '2/27/19', '2/27/20',
       '2/28/19', '2/28/20', '2/29/20', '2/3/19', '2/3/20', '2/4/19',
       '2/4/20', '2/5/19', '2/5/20', '2/6/19', '2/6/20', '2/7/19',
       '2/7/20', '2/8/19', '2/8/20', '2/9/19', '2/9/20', '3/1/19',
       '3/1/20', '3/10/19', '3/10/20', '3/11/19', '3/11/20', '3/12/19',
       '3/12/20', '3/13/19', '3/13/20', '3/14/19', '3/14/20', '3/15/19',
       '3/15/20', '3/16/19', '3/16/20', '3/17/19', '3/17/20', '3/18/19',
       '3/18/20', '3/19/19', '3/19/20', '3/2/19', '3/2/20', '3/20/19',
       '3/20/20', '3/21/19', '3/21/20', '3/22/19', '3/22/20', '3/23/19',
       '3/23/20', '3/24/19', '3/24/20', '3/25/19', '3/25/20', '3/26/19',
       '3/26/20', '3/27/19', '3/27/20', '3/28/19', '3/28/20', '3/29/19',
       '3/29/20', '3/3/19', '3/3/20', '3/30/19', '3/30/20', '3/31/19',
       '3/31/20', '3/4/19', '3/4/20', '3/5/19', '3/5/20', '3/6/19',
       '3/6/20', '3/7/19', '3/7/20', '3/8/19', '3/8/20', '3/9/19',
       '3/9/20', '4/1/19', '4/1/20', '4/10/19', '4/10/20', '4/11/19',
       '4/11/20', '4/12/19', '4/12/20', '4/13/19', '4/13/20', '4/14/19',
       '4/14/20', '4/15/19', '4/15/20', '4/16/19', '4/16/20', '4/17/19',
       '4/17/20', '4/18/19', '4/18/20', '4/19/19', '4/19/20', '4/2/19',
       '4/2/20', '4/20/19', '4/20/20', '4/21/19', '4/21/20', '4/22/19',
       '4/22/20', '4/23/19', '4/23/20', '4/24/19', '4/24/20', '4/25/19',
       '4/25/20', '4/26/19', '4/26/20', '4/27/19', '4/27/20', '4/28/19',
       '4/28/20', '4/29/19', '4/29/20', '4/3/19', '4/3/20', '4/30/19',
       '4/30/20', '4/4/19', '4/4/20', '4/5/19', '4/5/20', '4/6/19',
       '4/6/20', '4/7/19', '4/7/20', '4/8/19', '4/8/20', '4/9/19',
       '4/9/20', '5/1/19', '5/1/20', '5/10/19', '5/10/20', '5/11/19',
       '5/11/20', '5/12/19', '5/12/20', '5/13/19', '5/13/20', '5/14/19',
       '5/14/20', '5/15/19', '5/15/20', '5/16/19', '5/16/20', '5/17/19',
       '5/17/20', '5/18/19', '5/18/20', '5/19/19', '5/19/20', '5/2/19',
       '5/2/20', '5/20/19', '5/20/20', '5/21/19', '5/21/20', '5/22/19',
       '5/22/20', '5/23/19', '5/23/20', '5/24/19', '5/24/20', '5/25/19',
       '5/25/20', '5/26/19', '5/26/20', '5/27/19', '5/27/20', '5/28/19',
       '5/28/20', '5/29/19', '5/29/20', '5/3/19', '5/3/20', '5/30/19',
       '5/30/20', '5/31/19', '5/31/20', '5/4/19', '5/4/20', '5/5/19',
       '5/5/20', '5/6/19', '5/6/20', '5/7/19', '5/7/20', '5/8/19',
       '5/8/20', '5/9/19', '5/9/20', '6/1/18', '6/1/19', '6/10/18',
       '6/10/19', '6/11/18', '6/11/19', '6/12/18', '6/12/19', '6/13/18',
       '6/13/19', '6/14/18', '6/14/19', '6/15/18', '6/15/19', '6/16/18',
       '6/16/19', '6/17/18', '6/17/19', '6/18/18', '6/18/19', '6/19/18',
       '6/19/19', '6/2/18', '6/2/19', '6/20/18', '6/20/19', '6/21/18',
       '6/21/19', '6/22/18', '6/22/19', '6/23/18', '6/23/19', '6/24/18',
       '6/24/19', '6/25/18', '6/25/19', '6/26/18', '6/26/19', '6/27/18',
       '6/27/19', '6/28/18', '6/28/19', '6/29/18', '6/29/19', '6/3/18',
       '6/3/19', '6/30/18', '6/30/19', '6/4/18', '6/4/19', '6/5/18',
       '6/5/19', '6/6/18', '6/6/19', '6/7/18', '6/7/19', '6/8/18',
       '6/8/19', '6/9/18', '6/9/19', '7/1/18', '7/1/19', '7/10/18',
       '7/10/19', '7/11/18', '7/11/19', '7/12/18', '7/12/19', '7/13/18',
       '7/13/19', '7/14/18', '7/14/19', '7/15/18', '7/15/19', '7/16/18',
       '7/16/19', '7/17/18', '7/17/19', '7/18/18', '7/18/19', '7/19/18',
       '7/19/19', '7/2/18', '7/2/19', '7/20/18', '7/20/19', '7/21/18',
       '7/21/19', '7/22/18', '7/22/19', '7/23/18', '7/23/19', '7/24/18',
       '7/24/19', '7/25/18', '7/25/19', '7/26/18', '7/26/19', '7/27/18',
       '7/27/19', '7/28/18', '7/28/19', '7/29/18', '7/29/19', '7/3/18',
       '7/3/19', '7/30/18', '7/30/19', '7/31/18', '7/31/19', '7/4/18',
       '7/4/19', '7/5/18', '7/5/19', '7/6/18', '7/6/19', '7/7/18',
       '7/7/19', '7/8/18', '7/8/19', '7/9/18', '7/9/19', '8/1/18',
       '8/1/19', '8/10/18', '8/10/19', '8/11/18', '8/11/19', '8/12/18',
       '8/12/19', '8/13/18', '8/13/19', '8/14/18', '8/14/19', '8/15/18',
       '8/15/19', '8/16/18', '8/16/19', '8/17/18', '8/17/19', '8/18/18',
       '8/18/19', '8/19/18', '8/19/19', '8/2/18', '8/2/19', '8/20/18',
       '8/20/19', '8/21/18', '8/21/19', '8/22/18', '8/22/19', '8/23/18',
       '8/23/19', '8/24/18', '8/24/19', '8/25/18', '8/25/19', '8/26/18',
       '8/26/19', '8/27/18', '8/27/19', '8/28/18', '8/28/19', '8/29/18',
       '8/29/19', '8/3/18', '8/3/19', '8/30/18', '8/30/19', '8/31/18',
       '8/31/19', '8/4/18', '8/4/19', '8/5/18', '8/5/19', '8/6/18',
       '8/6/19', '8/7/18', '8/7/19', '8/8/18', '8/8/19', '8/9/18',
       '8/9/19', '9/1/18', '9/1/19', '9/10/18', '9/10/19', '9/11/18',
       '9/11/19', '9/12/18', '9/12/19', '9/13/18', '9/13/19', '9/14/18',
       '9/14/19', '9/15/18', '9/15/19', '9/16/18', '9/16/19', '9/17/18',
       '9/17/19', '9/18/18', '9/18/19', '9/19/18', '9/19/19', '9/2/18',
       '9/2/19', '9/20/18', '9/20/19', '9/21/18', '9/21/19', '9/22/18',
       '9/22/19', '9/23/18', '9/23/19', '9/24/18', '9/24/19', '9/25/18',
       '9/25/19', '9/26/18', '9/26/19', '9/27/18', '9/27/19', '9/28/18',
       '9/28/19', '9/29/18', '9/29/19', '9/3/18', '9/3/19', '9/30/18',
       '9/30/19', '9/4/18', '9/4/19', '9/5/18', '9/5/19', '9/6/18',
       '9/6/19', '9/7/18', '9/7/19', '9/8/18', '9/8/19', '9/9/18',
       '9/9/19'], dtype=object)